name: Run Pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls your repo into the GitHub runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Match your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt

      - name: Run tests
        run: pytest --cov  # Runs pytest with coverage reporting